; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[backup_migrate][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[calendar][subdir] = "contrib"

projects[colorbox][subdir] = "contrib"

projects[context][subdir] = "contrib"

projects[date][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[field_group][subdir] = "contrib"

projects[omega_tools][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[views][subdir] = "contrib"

projects[wysiwyg][subdir] = "contrib"

projects[zenophile][subdir] = "contrib"

; Themes
projects[] = "adaptivetheme"
projects[] = "omega"
projects[] = "beta"
projects[] = "boilerplate"
projects[] = "interactive_media"
projects[] = "pixture_reloaded"
projects[] = "typebased"
projects[] = "zen"
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[drupalbase][download][type] = ""
projects[drupalbase][download][url] = ""
projects[drupalbase][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[drupalbase_theme][download][type] = ""
projects[drupalbase_theme][download][url] = ""
projects[drupalbase_theme][type] = "theme"

